import type { NextPage } from "next";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useEffect } from "react";

// @ts-ignore: Unreachable code error
const Home: NextPage = ({ host }) => {
  const router = useRouter();
  useEffect(() => {
    console.log("🚀 ~ file: index.tsx ~ line 11 ~ router", router);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>This is NEXT 1 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next 1 App!</h1>
        <h2>{host}</h2>
      </main>
      <Link href="/_one">
        <a>_one</a>
      </Link>
      <Link href="/_two">
        <a>_two</a>
      </Link>
      <Link href={`${host}/two`}>
        <a>NEXT2</a>
      </Link>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

Home.getInitialProps = async (ctx) => {
  const { req } = ctx;
  // console.log("🚀 ~ file: index.tsx ~ line 51 ~ req", req?.headers);
  // @ts-ignore: Unreachable code error
  // const protocol = req.headers.referer.split("://")[0];
  // fullUrl = req.protocol + '://' + req.get('host') + req.originalUrl
  return { host: "http" + "://" + req?.headers.host };
};
export default Home;
